name: Enable maintenance for all FIs
on:
  workflow_dispatch:
    inputs:
      Platform:
        description: 'Choose for which platform we are bringing up the maintenance page'
        required: true
        default: 'web'
        type: choice
        options:
          - web
          - mobile
      Toggle:
        description: 'Choose if you want to eanble or disable maintenance page for all FIs '
        required: true
        default: 'enable'
        type: choice
        options:
          - enable
          - disable
jobs:
    update-mobile-cloudflare-data:
        if: ${{inputs.Platform == 'mobile'}}
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          - name: Read list of All FIs
            id: read-json
            run: |
              # Read the contents of All_FIs.json into an environment variable
              jq -c . ./.github/workflows/all_fi.json > single-line-mobile-data.json
              json_data=$(cat single-line-mobile-data.json)
              echo "mobile-data=$json_data" >> $GITHUB_OUTPUT
              echo $json_data

            
          - name: Enable maintenance page
            if: ${{ inputs.Toggle == 'enable' }}
            run: |
                curl -kv --location --request PUT 'https://api.cloudflare.com/client/v4/accounts/6deff3dcb08cded6b6a16a253c16f672/storage/kv/namespaces/2593f0624a5f4142b8361279d9ead704/bulk' \
                --header 'Content-Type: application/json' \
                --header 'Authorization: ${{ secrets.CLOUDFLARE_API_TOKEN }}' \
                --data '${{ steps.read-json.outputs.mobile-data }}'
            
            
          - name: Disable maintenance page
            if: ${{ inputs.Toggle == 'disable' }}
            run: |
                curl -kv --location --request POST 'https://api.cloudflare.com/client/v4/accounts/6deff3dcb08cded6b6a16a253c16f672/storage/kv/namespaces/2593f0624a5f4142b8361279d9ead704/bulk/delete' \
                --header 'Content-Type: application/json' \
                --header 'Authorization: ${{ secrets.CLOUDFLARE_API_TOKEN }}' 
                # --data '${{ steps.read-json.outputs.mobile-data }}'
    
    update-web-cloudflare-data:
        if: ${{inputs.Platform == 'web'}}
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3
          -  name: Echo input vars
             run: | 
               echo "${{inputs.Toggle}}"
          - name: Read list of All FIs
            id: read-json
            run: |
              # Read the contents of All_FIs.json into an environment variable
              jq -c . ./.github/workflows/all_fi.json > single-line-web-data.json
              json_data=$(cat single-line-web-data.json)
              echo "web-data=$json_data" >> $GITHUB_OUTPUT
              echo $json_data
          - name: Enable maintenance page
            if: ${{ inputs.Toggle == 'enable' }}
            run: |
                curl -kv --location --request PUT 'https://api.cloudflare.com/client/v4/accounts/6deff3dcb08cded6b6a16a253c16f672/storage/kv/namespaces/9845eb89c99a4edf94a01ad7a40fcf76/bulk' \
                --header 'Content-Type: application/json' \
                --header 'Authorization: ${{ secrets.CLOUDFLARE_API_TOKEN }}' \
                --data '${{ steps.read-json.outputs.web-data }}'
            
          - name: Disable maintenance page
            if: ${{ inputs.Toggle == 'disable' }}
            run: |
                curl -kv --location --request POST 'https://api.cloudflare.com/client/v4/accounts/6deff3dcb08cded6b6a16a253c16f672/storage/kv/namespaces/9845eb89c99a4edf94a01ad7a40fcf76/bulk/delete' \
                --header 'Content-Type: application/json' \
                --header 'Authorization: ${{ secrets.CLOUDFLARE_API_TOKEN }}' 
            
             