name: CloudFlare Maintenance Test

# Trigger the workflow when data.json is modified
on:
  workflow_dispatch:
  push:
    paths:
      - 'web-data.json'

jobs:
  update-cloudflare-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Read data from data.json
      id: read-json
      run: |
        # Read the contents of data.json into an environment variable
        echo "DATA=$(cat web-data.json)"
    - name: Update Cloudflare KV Store
      run: |
        curl -vk --location --request PUT 'https://api.cloudflare.com/client/v4/accounts/6deff3dcb08cded6b6a16a253c16f672/storage/kv/namespaces/2593f0624a5f4142b8361279d9ead704/bulk' \
        --header 'Content-Type: application/json' \
        --header 'Authorization: ${{ secrets.CLOUDFLARE_API_TOKEN }}' \
        --data '$DATA'
      # Replace this with your real Cloudflare token in the repository secrets settings
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        DATA: ${{ env.DATA }}
