name: Cloudflare Maintenance

on:
  workflow_dispatch:
    inputs:
      Platform:
        description: 'Choose for which platform we are bringing up the maintenance page'
        required: true
        default: 'web'
        type: choice
        options:
          - web
          - mobile
  push:
    paths:
      - 'mobile-data.json'
      - 'web-data.json'

jobs:
  update-mobile-cloudflare-data:
    env:
      CF_AUTH_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    if: ${{inputs.Platform == 'mobile'}}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Read data from mobile-data.json
      id: read-json
      run: |
        # Read the contents of data.json into an environment variable
        json_data=$(cat mobile-data.json)
        echo "::set-output name=mobile-data::$json_data"

    - name: Update Cloudflare KV Store
      run: |
        curl -kv --location --request PUT 'https://api.cloudflare.com/client/v4/accounts/6deff3dcb08cded6b6a16a253c16f672/storage/kv/namespaces/2593f0624a5f4142b8361279d9ead704/bulk' \
        --header 'Content-Type: application/json' \
        --header 'Authorization: ${{ secrets.CLOUDFLARE_API_TOKEN }}' \
        --data '${{ steps.read-json.outputs.mobile-data }}'

  
      
  update-web-cloudflare-data:
    if: ${{inputs.Platform == 'web'}}
    runs-on: ubuntu-latest
    env:
      CF_AUTH_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Read data from web-data.json
      id: read-json
      run: |
        # Read the contents of data.json into an environment variable
        json_data=$(cat web-data.json | base64 -w 0)
        echo "data=$json_data" >> $GITHUB_OUTPUT
        

    - name: Update Cloudflare KV Store
      run: |
        curl -kv --location --request PUT 'https://api.cloudflare.com/client/v4/accounts/6deff3dcb08cded6b6a16a253c16f672/storage/kv/namespaces/2593f0624a5f4142b8361279d9ead704/bulk' \
        --header 'Content-Type: application/json' \
        --header 'Authorization: ${{ secrets.CLOUDFLARE_API_TOKEN }}' \
        --data '${{ steps.read-json.outputs.web-data }}'
    
    - name: Get the KV details
      run: |
        curl --location 'https://api.cloudflare.com/client/v4/accounts/6deff3dcb08cded6b6a16a253c16f672/storage/kv/namespaces/9845eb89c99a4edf94a01ad7a40fcf76/keys' \
        --header '${{ secrets.CLOUDFLARE_API_TOKEN }}' \
        --header 'Content-Type: application/json' \
  
