name: Cloudflare Maintenance

on:
  workflow_dispatch:
    inputs:
      Platform:
        description: 'Choose for which platform we are bringing up the maintenance page'
        required: true
        default: 'web'
        type: choice
        options:
          - web
          - mobile
      API:
        description: 'Choose whether to add or remove FIs from the maintenance'
        required: true
        default: 'add'
        type: choice
        options:
          - add
          - remove

jobs:
  add-mobile-maintenance-cloudflare:
    if: ${{inputs.Platform == 'mobile'&& inputs.API == 'add'}}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Read data from mobile-data.json
      id: read-json
      run: |
        # Read the contents of data.json into an environment variable
        json_data=$(cat mobile-data.json)
        echo "::set-output name=mobile-data::$json_data"

    - name: Update Cloudflare KV Store
      env:
        CF_AUTH_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      run: |
        curl -kv --location --request PUT 'https://api.cloudflare.com/client/v4/accounts/6deff3dcb08cded6b6a16a253c16f672/storage/kv/namespaces/2593f0624a5f4142b8361279d9ead704/bulk' \
        --header 'Content-Type: application/json' \
        --header 'Authorization: ${{ secrets.CLOUDFLARE_API_TOKEN }}' \
        --data '${{ steps.read-json.outputs.mobile-data }}'  
      
  add-web-maintenance-cloudflare:
    if: ${{inputs.Platform == 'web' && inputs.API == 'add'}}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Read data from web-data.json
      id: read-json
      run: |
        # Read the contents of data.json into an environment variable
        jq -c . web-data.json > single-line-web-data.json
        json_data=$(cat single-line-web-data.json)
        echo "data=$json_data" >> $GITHUB_OUTPUT
        echo $json_data
        

    - name: Update Cloudflare KV Store
      run: |
        curl --location --request PUT 'https://api.cloudflare.com/client/v4/accounts/6deff3dcb08cded6b6a16a253c16f672/storage/kv/namespaces/9845eb89c99a4edf94a01ad7a40fcf76/bulk' \
        --header 'Content-Type: application/json' \
        --header 'Authorization: ${{ secrets.CLOUDFLARE_API_TOKEN }}' \
        --data '${{ steps.read-json.outputs.data }}'
  
  remove-mobile-maintenance-cloudflare:
    if: ${{inputs.Platform == 'mobile'&& inputs.API == 'remove'}}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Read data from mobile-data-remove.json
      id: read-json
      run: |
        # Read the contents of data.json into an environment variable
        json_data=$(cat mobile-data-remove.json)
        echo "::set-output name=mobile-data-remove::$json_data"

    - name: Update Cloudflare KV Store
      env:
        CF_AUTH_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      run: |
        curl -kv --location --request POST 'https://api.cloudflare.com/client/v4/accounts/6deff3dcb08cded6b6a16a253c16f672/storage/kv/namespaces/2593f0624a5f4142b8361279d9ead704/bulk' \
        --header 'Content-Type: application/json' \
        --header 'Authorization: ${{ secrets.CLOUDFLARE_API_TOKEN }}' \
        --data '${{ steps.read-json.outputs.mobile-data-remove }}'  
      
  remove-web-maintenance-cloudflare:
    if: ${{inputs.Platform == 'web' && inputs.API == 'remove'}}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Read data from web-data-remove.json
      id: read-json
      run: |
        # Read the contents of data.json into an environment variable
        jq -c . web-data-remove.json > single-line-web-data.json
        json_data=$(cat single-line-web-data.json)
        echo "data-remove=$json_data" >> $GITHUB_OUTPUT
        echo $json_data
        

    - name: Update Cloudflare KV Store
      run: |
        curl --location --request POST 'https://api.cloudflare.com/client/v4/accounts/6deff3dcb08cded6b6a16a253c16f672/storage/kv/namespaces/9845eb89c99a4edf94a01ad7a40fcf76/bulk/delete' \
        --header 'Content-Type: application/json' \
        --header 'Authorization: ${{ secrets.CLOUDFLARE_API_TOKEN }}' \
        --data '${{ steps.read-json.outputs.data-remove }}'    
  
