name: Cloudflare Maintenance Dynamic

on:
  workflow_dispatch:
    inputs:
      Platform:
        description: 'Choose for which platform we are bringing up the maintenance page'
        required: true
        default: 'web'
        type: choice
        options:
          - web
          - mobile
      API:
        description: 'Choose whether to add or remove FIs from the maintenance'
        required: true
        default: 'add'
        type: choice
        options:
          - add
          - remove
      Domains:
        description: 'Comma-separated list of domains'
        required: true
        default: ''

jobs:
  add-maintenance-mobile-cloudflare:
    environment: cf-nonprd
    if: ${{ inputs.API == 'add' && inputs.Platform == 'mobile' }}
    runs-on: ubuntu-latest
    outputs:
      data: steps.format-json.outputs.formatted_data
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Format domains JSON
        id: format-json
        env:
          DOMAINS: ${{ inputs.Domains }}
        run: |
          python3 <<EOF
          import json
      
          # Split and clean the comma-separated domain list
          domains = [domain.strip() for domain in '${DOMAINS}'.split(',') if domain.strip()]
          formatted_data = [{"key": domain, "value": "true"} for domain in domains]
      
          # Write formatted JSON to a file
          with open('data-mobile.json', 'w') as f:
              json.dump(formatted_data, f, indent=2)
          EOF
          # Output formatted JSON as a single line for environment variable
          echo "formatted_data=$(jq -c . data-mobile.json)" >> $GITHUB_OUTPUT
      - name: Display formatted JSON for review
        run: |
          echo "Domains to be processed:"
          cat data-mobile.json
  apply-maintenance-mobile-cloudflare:
    environment: cf-nonprd
    if: ${{ inputs.API == 'add' && inputs.Platform == 'mobile' }}
    runs-on: ubuntu-latest
    needs: add-maintenance-mobile-cloudflare
    steps:
      - name: Update Cloudflare KV Store
        env:
          CF_AUTH_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          FORMATTED_DATA: ${{ needs.add-maintenance-mobile-cloudflare.outputs.data }}
        run: |
          curl -vk --location --request PUT 'https://api.cloudflare.com/client/v4/accounts/6deff3dcb08cded6b6a16a253c16f672/storage/kv/namespaces/2593f0624a5f4142b8361279d9ead704/bulk' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: ${{ secrets.CLOUDFLARE_API_TOKEN }}' \
          --data "$FORMATTED_DATA"
  remove-maintenance-mobile-cloudflare:
    environment: cf-nonprd
    if: ${{ inputs.API == 'remove' && inputs.Platform == 'mobile' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Format domains for deletion JSON
        id: format-delete-json
        env:
          DOMAINS: ${{ inputs.Domains }}
        run: |
          python3 <<EOF
          import json
      
          # Split and clean the comma-separated domain list
          domains = [domain.strip() for domain in '${DOMAINS}'.split(',') if domain.strip()]
      
          # Write formatted JSON list for deletion
          with open('delete-data-mobile.json', 'w') as f:
              json.dump(domains, f)
          EOF
      
          # Output formatted JSON as a single line for environment variable
          echo "delete_data=$(jq -c . delete-data-mobile.json)" >> $GITHUB_ENV
      - name: Display formatted JSON for review
        run: |
          echo "Domains to be processed:"
          cat delete-data-mobile.json
      - name: Update Cloudflare KV Store (Delete)
        env:
          CF_AUTH_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          DELETE_DATA: ${{ env.delete_data }}
        run: |
          curl --location --request POST 'https://api.cloudflare.com/client/v4/accounts/6deff3dcb08cded6b6a16a253c16f672/storage/kv/namespaces/2593f0624a5f4142b8361279d9ead704/bulk/delete' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: ${{ secrets.CLOUDFLARE_API_TOKEN }}' \
          --data "$DELETE_DATA"

  add-maintenance-web-cloudflare:
    if: ${{ inputs.API == 'add' && inputs.Platform == 'web' }}
    runs-on: ubuntu-latest
    outputs:
      web-data: ${{ steps.format-json.outputs.formatted_data }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Format domains JSON
        id: format-json
        env:
          DOMAINS: ${{ inputs.Domains }}
        run: |
          python3 <<EOF
          import json
      
          # Split and clean the comma-separated domain list
          domains = [domain.strip() for domain in '${DOMAINS}'.split(',') if domain.strip()]
          formatted_data = [{"key": domain, "value": "true"} for domain in domains]
      
          # Write formatted JSON to a file
          with open('data-web.json', 'w') as f:
              json.dump(formatted_data, f, indent=2)
          EOF
          # Output formatted JSON as a single line for environment variable
          echo "formatted_data=$(jq -c . data-web.json)" >> $GITHUB_OUTPUT
      - name: Display formatted JSON for review
        run: |
          echo "Domains to be processed:"
          cat data-web.json

  apply-maintenance-web-cloudflare:
    environment: cf-nonprd
    if: ${{ inputs.API == 'add' && inputs.Platform == 'web' }}
    runs-on: ubuntu-latest
    needs: add-maintenance-web-cloudflare
    steps:
      - name: Update Cloudflare KV Store
        env:
          CF_AUTH_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          FORMATTED_DATA: ${{ needs.add-maintenance-web-cloudflare.outputs.web-data }}
        run: |
          curl -vk --location --request PUT 'https://api.cloudflare.com/client/v4/accounts/6deff3dcb08cded6b6a16a253c16f672/storage/kv/namespaces/9845eb89c99a4edf94a01ad7a40fcf76/bulk' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: ${{ secrets.CLOUDFLARE_API_TOKEN }}' \
          --data "$FORMATTED_DATA"
    
  remove-maintenance-web-cloudflare:
    if: ${{ inputs.API == 'remove' && inputs.Platform == 'web' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Format domains for deletion JSON
        id: format-delete-json
        env:
          DOMAINS: ${{ inputs.Domains }}
        run: |
          python3 <<EOF
          import json
      
          # Split and clean the comma-separated domain list
          domains = [domain.strip() for domain in '${DOMAINS}'.split(',') if domain.strip()]
      
          # Write formatted JSON list for deletion
          with open('delete-data-web.json', 'w') as f:
              json.dump(domains, f)
          EOF
      
          # Output formatted JSON as a single line for environment variable
          echo "delete_data=$(jq -c . delete-data-web.json)" >> $GITHUB_ENV
      - name: Display formatted JSON for review
        run: |
          echo "Domains to be processed:"
          cat delete-data-web.json
      - name: Update Cloudflare KV Store (Delete)
        env:
          CF_AUTH_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          DELETE_DATA: ${{ env.delete_data }}
        run: |
          curl --location --request POST 'https://api.cloudflare.com/client/v4/accounts/6deff3dcb08cded6b6a16a253c16f672/storage/kv/namespaces/9845eb89c99a4edf94a01ad7a40fcf76/bulk/delete' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: ${{ secrets.CLOUDFLARE_API_TOKEN }}' \
          --data "$DELETE_DATA"

