name: Cloudflare Maintenance Test

on:
  workflow_dispatch:
    inputs:
      Platform:
        description: 'Choose for which platform we are bringing up the maintenance page'
        required: true
        default: 'web'
        type: choice
        options:
          - web
          - mobile
      API:
        description: 'Choose whether to add or remove FIs from the maintenance'
        required: true
        default: 'add'
        type: choice
        options:
          - add
          - remove
      Domains:
        description: 'Comma-separated list of domains'
        required: true
        default: ''

jobs:
  add-maintenance-cloudflare:
    if: ${{ inputs.API == 'add' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Format domains JSON
        id: format-json
        env:
          DOMAINS: ${{ inputs.Domains }}
        run: |
          python3 <<EOF
          import json
      
          # Split and clean the comma-separated domain list
          domains = [domain.strip() for domain in '${DOMAINS}'.split(',') if domain.strip()]
          formatted_data = [{"key": domain, "value": "true"} for domain in domains]
      
          # Write formatted JSON to a file
          with open('data.json', 'w') as f:
              json.dump(formatted_data, f, indent=2)
          EOF
          # Output formatted JSON as a single line for environment variable
          echo "formatted_data=$(jq -c . data.json)" >> $GITHUB_ENV
      - name: Update Cloudflare KV Store
        env:
          CF_AUTH_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          FORMATTED_DATA: ${{ env.formatted_data }}
        run: |
          curl --location --request PUT 'https://api.cloudflare.com/client/v4/accounts/6deff3dcb08cded6b6a16a253c16f672/storage/kv/namespaces/2593f0624a5f4142b8361279d9ead704/bulk' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: ${{ secrets.CLOUDFLARE_API_TOKEN }}' \
          --data "$FORMATTED_DATA"

  remove-maintenance-cloudflare:
    if: ${{ inputs.API == 'remove' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Format domains for deletion JSON
        id: format-delete-json
        env:
          DOMAINS: ${{ inputs.Domains }}
        run: |
          # Convert comma-separated list of domains into JSON format for deletion
          import json

          domains = [domain.strip() for domain in '${DOMAINS}'.split(',') if domain.strip()]
          with open('delete-data.json', 'w') as f:
              json.dump(domains, f)

          # Output formatted JSON as a single line
          echo "delete_data=$(jq -c . delete-data.json)" >> $GITHUB_ENV

      - name: Update Cloudflare KV Store (Delete)
        env:
          CF_AUTH_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          DELETE_DATA: ${{ env.delete_data }}
        run: |
          curl --location --request POST 'https://api.cloudflare.com/client/v4/accounts/6deff3dcb08cded6b6a16a253c16f672/storage/kv/namespaces/2593f0624a5f4142b8361279d9ead704/bulk/delete' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: ${{ secrets.CLOUDFLARE_API_TOKEN }}' \
          --data "$DELETE_DATA"
